AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'

#################### Layout ###########################

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

#################### Metrics ###############################

Metrics/BlockLength:
  Enabled: true
  CountComments: false
  Max: 25
  ExcludedMethods:
    - refine
    - describe
  Exclude:
    - '**/*.gemspec'

#################### Style ###############################

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
