name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5 

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: add PostgreSQL dependencies
      run: |
        sudo apt-get update
        sudo apt-get -yqq install libpq-dev
    - name: Build and test Rails
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn install --check-files
        bundle exec rails webpacker:compile
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails test
        bundle exec rubocop
